

Data_path:
  raw_label_image_dir: '/ai/data/flare2023/imagesTr2200'
  raw_label_seg_dir: '/ai/data/flare2023/labelsTr2200'

  val_image_dir: '/ai/data/flare2023/val50'
  val_seg_dir: '/ai/data/flare2023/val-gt'

  predict_data_dir: '/ai/data/flare2023/not_full_abdomen_label_case_predict'
  # preprocess_label_data_dir: '/ai/data/flare2023/preprocessFirstStageLabelData2200_192192192'
  # preprocess_label_data_dir: '/ai/data/flare2023/preprocessFirstStageLabelData2200_192192192_NC'
  preprocess_label_data_dir: '/ai/data/flare2023/preprocessFirstStageLabelData2200_128128128_NC'
  # preprocess_label_data_dir: '/ai/data/flare2023/preprocessFirstStageLabelData2200_128128128'

  preprocess_val_data_dir: '/ai/data/flare2023/preprocessFirstStageVal_128128128'
  checkpoint_dir: '/ai/code/Flare2023/checkpoint/first_stage'
Dataloader:
  data_size: [128,128,128]
  batch_size: 2
Trainer:
  do_dummy_2d_data_aug: False
  copy_paste: False
  initial_lr: 1e-2
  weight_decay: 3e-5
  num_iterations_per_epoch: 250
  num_val_iterations_per_epoch: 50
  num_epochs: 500
  save_every: 50
  CGN: False

Model:
  UNet_class_name: ResidualEncoderUNet
  num_classes: 2
  n_conv_per_stage_decoder: 2 
  n_conv_per_stage_encoder: 2
  UNet_base_num_features: 16
  unet_max_num_features: 320
  conv_kernel_sizes: [[3,3,3],[3,3,3],[3,3,3],[3,3,3],[3,3,3],[3,3,3]]
  pool_op_kernel_sizes: [[1,1,1],[2,2,2],[2,2,2],[2,2,2],[2,2,2],[2,2,2]]
  num_input_channels: 1
  deep_supervision: True
  dropout_p: 0
  is_BN: False



Postprocess:
  area_least: 100
  topk: 30


Loss:
  ce_weight: 1
  dice_weight: 1
  classes_weight: [1,1]
  main_loss_weight: 1
  auxiliary_loss_weight: 2








